### ISSUE TITLE
Fix the https option

### ISSUE THREAD

**Issue by jsonthebson** [kacollins/2022-07-workshop#3]
Currently, Emily has workshop.techlahoma.org set up through techlahoma and dnsimple. She needs help figuring out where https:// will work, since http:// works.

**Comment by pythoninthegrass** [comment]
Working with Emily to add the ~~[A record](https://support.dnsimple.com/articles/manage-a-record/)~~ [EDIT: URL record]. Will update the issue after it's done.

**Comment by pythoninthegrass** [comment]
It wasn’t an [A record (IP address)](https://support.dnsimple.com/articles/differences-between-a-cname-alias-url/), was a combination of an [HTTPS URL record (redirect)](https://support.dnsimple.com/articles/redirector/#https-redirects) and setting up a [wildcard cert (LetsEncrypt certificate authority)](https://blog.dnsimple.com/2019/07/https-redirector/) for naked domains.

![wildcard](https://user-images.githubusercontent.com/4097471/177012651-ae39a2d1-af85-46ef-b5fe-a4851b212e14.png)

Now it's possible to enter https://workshop.techlahoma.org or any other subdomain (e.g., https://uxok.techlahoma.org) that use URL redirects. LetsEncrypt certs automatically renew every 90 days.
